interface TypeAccess {
  name: string;
}

interface TableHeader {
  name: string;
}

export const typeAccess: TypeAccess[] = [
  { name: '+1' },
  { name: '10x2' },
  { name: '4Cs' },
  { name: 'Analizar movimientos' },
  { name: 'Análisis de estilo/error' },
  { name: 'Análizar oraciones' },
  { name: 'Brújula' },
  { name: 'Caracterizar' },
  { name: 'Debate' },
  { name: 'Demostrar' },
  { name: 'Dibujar' },
  { name: 'Dramatizar' },
  { name: 'Ejemplificar' },
  { name: 'Esquemas' },
  { name: 'Estudiar casos' },
  { name: 'Experimentos' },
  { name: 'Explorar' },
  { name: 'Fotografía' },
  { name: 'Gráficos' },
  { name: 'Hipótesis' },
  { name: 'Identificar' },
  { name: 'Inferir' },
  { name: 'Investigar' },
  { name: 'Juegos de roles' },
  { name: 'Lectura crítica' },
  { name: 'Mapa conceptual' },
  { name: 'Mapa mental' },
  { name: 'Modelar' },
  { name: 'Narrar' },
  { name: 'Observación' },
  { name: 'Organizadores gráficos' },
  { name: 'Papel de roles' },
  { name: 'Plantear preguntas' },
  { name: 'Predicción' },
  { name: 'Presentación' },
  { name: 'Problemas' },
  { name: 'Proyectos' },
  { name: 'Recopilar datos' },
  { name: 'Reflexionar' },
  { name: 'Resolver' },
  { name: 'Simulación' },
  { name: 'Sintetizar' },
  { name: 'Sondeo' },
  { name: 'Taller' },
  { name: 'Test' },
  { name: 'Trabajo en grupo' },
  { name: 'Trabajo en parejas' },
  { name: 'Uso de tecnologías' },
  { name: 'Visita de campo' },
  { name: 'Aplicar' },
  { name: 'Clasificar' },
  { name: 'Comparar' },
  { name: 'Conectar' },
  { name: 'Construir' },
  { name: 'Contextualizar' },
  { name: 'Contrastar' },
  { name: 'Convertir' },
  { name: 'Crear' },
  { name: 'Criticar' },
  { name: 'Cuestionar' },
  { name: 'Defender' },
  { name: 'Deducir' },
  { name: 'Descubrir' },
  { name: 'Describir' },
  { name: 'Diseñar' },
  { name: 'Distinguir' },
  { name: 'Dividir' },
  { name: 'Elaborar' },
  { name: 'Evaluar' },
  { name: 'Explicar' },
  { name: 'Generalizar' },
  { name: 'Identificar problemas' },
  { name: 'Imitar' },
  { name: 'Indagar' },
  { name: 'Integrar' },
  { name: 'Interpretar' },
  { name: 'Inventar' },
  { name: 'Justificar' },
  { name: 'Localizar' },
  { name: 'Modificar' },
  { name: 'Organizar' },
  { name: 'Planificar' },
  { name: 'Predecir' },
  { name: 'Preparar' },
  { name: 'Probar' },
  { name: 'Proponer' },
  { name: 'Recomendar' },
  { name: 'Relacionar' },
  { name: 'Revisar' },
  { name: 'Seleccionar' },
  { name: 'Separar' },
  { name: 'Simplificar' },
  { name: 'Simular' },
  { name: 'Subdividir' },
  { name: 'Sugerir' },
  { name: 'Validar' },
  { name: 'Verificar' },
  { name: 'Analizar datos' },
  { name: 'Aplicar conceptos' },
  { name: 'Crear modelos' },
  { name: 'Desarrollar hipótesis' },
  { name: 'Desarrollar teorías' },
  { name: 'Diseñar experimentos' },
  { name: 'Evaluar resultados' },
  { name: 'Formular teorías' },
  { name: 'Generar preguntas' },
  { name: 'Identificar patrones' },
  { name: 'Interpretar datos' },
  { name: 'Observar fenómenos' },
  { name: 'Planificar investigaciones' },
  { name: 'Plantear hipótesis' },
  { name: 'Probar teorías' },
  { name: 'Realizar estudios' },
  { name: 'Recoger datos' },
  { name: 'Refinar hipótesis' },
  { name: 'Simular fenómenos' },
  { name: 'Validar hipótesis' },
  { name: 'Analizar contextos' },
  { name: 'Aplicar estrategias' },
  { name: 'Crear estrategias' },
  { name: 'Desarrollar habilidades' },
  { name: 'Desarrollar tácticas' },
  { name: 'Diseñar planes' },
  { name: 'Evaluar tácticas' },
  { name: 'Formular estrategias' },
  { name: 'Generar ideas' },
  { name: 'Identificar problemas' },
  { name: 'Implementar soluciones' },
  { name: 'Observar situaciones' },
  { name: 'Planificar soluciones' },
  { name: 'Plantear soluciones' },
  { name: 'Probar estrategias' },
  { name: 'Realizar análisis' },
  { name: 'Recoger información' },
  { name: 'Refinar estrategias' },
  { name: 'Simular escenarios' },
  { name: 'Validar estrategias' },
  { name: 'Analizar procesos' },
  { name: 'Aplicar conocimientos' },
  { name: 'Crear procedimientos' },
  { name: 'Desarrollar procesos' },
  { name: 'Desarrollar procedimientos' },
  { name: 'Diseñar procesos' },
  { name: 'Evaluar procesos' },
  { name: 'Formular procesos' },
  { name: 'Generar procedimientos' },
  { name: 'Identificar fallos' },
  { name: 'Implementar procesos' },
  { name: 'Observar procedimientos' },
  { name: 'Planificar procedimientos' },
  { name: 'Plantear procedimientos' },
  { name: 'Probar procedimientos' },
  { name: 'Realizar procedimientos' },
  { name: 'Recoger resultados' },
  { name: 'Refinar procesos' },
  { name: 'Simular procedimientos' },
  { name: 'Validar procesos' },
];

export const tableHeaders: TableHeader[] = [
  { name: 'Tipo de acceso' },
  { name: 'Ambiente natural y social' },
  { name: 'Arte' },
  { name: 'Educación física' },
  { name: 'Música' },
  { name: 'Nutrición' },
  { name: 'Prácticas del lenguaje' },
  { name: 'Drama' },
  { name: 'Ciencias sociales' },
  { name: 'Ciencias naturales' },
  { name: 'Social studies' },
  { name: 'Sociology' },
  { name: 'NTICx' },
  { name: 'Matemáticas' },
  { name: 'Lengua' },
  { name: 'Historia' },
  { name: 'Geografía' },
  { name: 'Ciencias' },
  { name: 'Tecnología' },
  { name: 'Literatura' },
  { name: 'Filosofía' },
  { name: 'Economía' },
  { name: 'Política' },
  { name: 'Derecho' },
  { name: 'Biología' },
  { name: 'Química' },
  { name: 'Física' },
  { name: 'Astronomía' },
  { name: 'Ecología' },
  { name: 'Arte visual' },
  { name: 'Música clásica' },
  { name: 'Teatro' },
  { name: 'Danza' },
  { name: 'Cultura' },
  { name: 'Comunicación' },
  { name: 'Deportes' },
  { name: 'Salud' },
  { name: 'Medio ambiente' },
  { name: 'Tecnologías emergentes' },
  { name: 'Desarrollo personal' },
  { name: 'Educación para la ciudadanía' },
  { name: 'Trabajo en equipo' },
  { name: 'Habilidades sociales' },
  { name: 'Ciencias de la computación' },
  { name: 'Diseño gráfico' },
  { name: 'Marketing' },
  { name: 'Gestión de proyectos' },
  { name: 'Investigación' },
  { name: 'Estadística' },
  { name: 'Liderazgo' },
];

